### ISSUE TITLE
Still shows 1.9.0a even on april 4, 2021

### ISSUE THREAD

**Issue by efdevelopers** [agronomru/ACNH-BCATs#10]
I've followed all steps and the title still shows 1.9.0a today on april 4, 2021.

The system is set to syncronize time over the internet and I have synced with the ntp server using switch-time app. Am I missing something?

**Comment by nicolmart** [comment]
Same happening to me, any news?

**Comment by agronomru** [comment]
I have no idea what you guys are doing wrong. It works for like 99% of people and most common issue is that people ignores the switch-time part of the guide.
If you're using a Mac this may help you: https://gbatemp.net/threads/acnh-bcat-forging.564556/page-6#post-9434956
But you don't have to unlink your Nintendo account, it changes nothing for BCATs.

**Comment by anthr76** [comment]
Linux user here. Quite baffling. I'd love to compare some things with a user that had it work..
