### ISSUE TITLE
Are you planning in release the 1.11.1 BCAT files version?

### ISSUE THREAD

**Issue by DomPedro25** [agronomru/ACNH-BCATs#12]
Hey, I'm really thankful for you work in disponibilizing this BCAT files for us. But I'm wondering if you plan to disponibilize the files of the current version as the Halloween event is approching!

**Comment by Wompatz** [comment]
No update so far? 🙁 Could somebody told us, what is the problem? Do you want donations?
Best regards

**Comment by Dfox444** [comment]
I definitely wouldn't mind the BCAT files for 1.11.1 so I can go back and do what I missed.

**Comment by agronomru** [comment]
Sorry, I'm not playing the game anymore, forgot about it.  
In case this site won't be up to date again, please check out  
https://gbatemp.net/threads/acnh-bcat-forging.564556/
