### ISSUE TITLE
1.11.1a release still shows as 1.11.1 in Animal Crossing

### ISSUE THREAD

**Issue by syberphunk** [agronomru/ACNH-BCATs#13]
Looks like this hasn't been updated fully/properly in the release? the files.meta for ItemDeli has been updated. Not seeing an appropriate EventDeli file if there's meant to be an event flag for this year's halloween?

Also no Jack for 31st of October's Halloween event.

**Comment by agronomru** [comment]
Follow the guide, use switch-time.  
I just tested it, works fine.

**Comment by syberphunk** [comment]
@agronomru For closure here, I discovered it's a problem with the lastest master of Ryujinx, but it works fine with the LDN build which is a bit older.

Thanks for providing the files.
