### ISSUE TITLE
why my version still shows 1.2.1a?

### ISSUE THREAD

**Issue by ssbg2** [agronomru/ACNH-BCATs#4]
Hi,thanks for this guide!
Last time I used jksv to inject BCAT files,it was success,game version shows 1.2.0a and soon I install the update patch to 1.2.1a. 
But today I almost tried everything:restore with or with not the passphrase.bin file;use switch-time and the tesla-menu ntp application to sync time,several times reboot the switch...but all of this didn't work,I still stuck in 1.2.1a.
There must be some thing i missed,But what is it?
Best regards.

**Comment by illyasever-lol** [comment]
you can use jksv make your bcat backup.take them to computer desktop.copy d bcat to your backup floder.at last take the floder to jksv floder and use it restore.play game,d version is done.

**Comment by ssbg2** [comment]
> you can use jksv make your bcat backup.take them to computer desktop.copy d bcat to your backup floder.at last take the floder to jksv floder and use it restore.play game,d version is done.

thanks,I do all this through mtp inside switch,but last time I do this with sd card reader,maybe this matters.
thanks again!

**Comment by igromanru** [comment]
Have you tried to follow the guide?

**Comment by ssbg2** [comment]
> Have you tried to follow the guide?
Sorry,The switch is not around when I came to work. I will tell you the result after trying in the evening. And if it is not successful, I will continue to try other ways. 
Thank you for your concern.

**Comment by agronomru** [comment]
The whole main site of this Repository is a step by step guide to activate BCATs.  
Please follow it exactly how it says.

**Comment by ssbg2** [comment]
I backup savedata with JKSV and deleted game after.
After reinstalled game(base+update+dlc),BCATS(1.2.1c),sync time(switch-time.nro),it shows 1.2.1c.
BUT It didn't work when I do the samething in sysnand CFW,I found it needs upgrading to 1.2.1d first,downgrade to 1.2.1c after in my case.
So if other people are in the same situation as me, you can try to reinstall the game after backing up the files,and follow the guide steps.
