### ISSUE TITLE
Game version says 1.6.0a instead of 1.6.0c

### ISSUE THREAD

**Issue by g333no** [agronomru/ACNH-BCATs#7]
I restored the BCAT files as normal, i already followed the guide previously and it always worked, but this time something isn't working because i'm only getting 1.6.0a instead of 1.6.0c. The thanksgiving event works (or rather, it shows up on the title screen) but christmas and new year's eve don't.
I haven't tried actually playing yet because i tried to restore everything first, i deleted both the game and saves and restored all of it but i still get 1.6.0a. What could be the issue here?

**Comment by deejay87** [comment]
Strange cause i try now to install and i have 1.6.0c

**Comment by g333no** [comment]
> 
> 
> Strange cause i try now to install and i have 1.6.0c

i tried restoring everything again and using switch time automatic time settings but it still says 1.6.0a
i also tried going to dec 31 with switch time and the new year's eve event seems to be there (as in, there's a countdown), but the game version is still 1.6.0a
I guess i'll keep playing normally while waiting for more news on the matter, maybe the issue is only with the version number but everything will work fine anyway?

**Comment by deejay87** [comment]
My daughter have test, and impossible to have the "C", stay on 1.6.0 , héhé, very strange, i don't have found how why this don't be take by the game

**Comment by igromanru** [comment]
Try redo the guide. All steps with setting the time are important and the key for successful activation.

**Comment by g333no** [comment]
> 
> 
> Try redo the guide. All steps with setting the time are important and the key for successful activation.

Already did that multiple times, i even deleted and reinstalled the game, deleted saves (which i later restored) and whatnot but it still doesn't move from 1.6.0a. Even searching on like gbatemp i read about people having the same issue and either they didn't solve it or solved it with the usual "nvm fixed ;)" without actually saying how they fixed it

**Comment by igromanru** [comment]
Have you tried to play around with switch-time homebrew for a bit?
Like setting the actual current time with Y and then change it and apply with A?
I would say if you see 1.6.0a it means that BCATs are installed properly, so my best bet is that the game doesn't detect the right date time to activate these events. But without reverse engineering the game nobody can tell you how it works exactly.
EDIT:
Is your Switch connected to internet?

**Comment by g333no** [comment]
> 
> 
> Have you tried to play around with switch-time homebrew for a bit?
> Like setting the actual current time with Y and then change it and apply with A?
> I would say if you see 1.6.0a it means that BCATs are installed properly, so my best bet is that the game doesn't detect the right date time to activate these events. But without reverse engineering the game nobody can tell you how it works exactly.
> EDIT:
> Is your Switch connected to internet?

yes of course, it's how i changed the date to check if the events were working or not. I tried both the automatic setting with Y and the manual one, it always says "Successfully set NetworkSystemClock" every time i try so it's not like switch time is not working, but it's no dice for the events.
Also yes, i tried both while connected and while in airplane mode
Keep in mind that as i said in my first post i never had to do this before, not even messing with switch time, everything always worked after just restoring the bcat.

**Comment by igromanru** [comment]
Sorry, I think I can't help you then. The big problem with activating Events were solved for most people by using switch-time and let the Switch think that the time is synchronized.  
Maybe something has changed with the latest Firmware? If you're on version 11.0.X. I'm still on 10.0.2. But this are just speculations.

**Comment by g333no** [comment]
> 
> 
> Sorry, I think I can't help you then. The big problem with activating Events were solved for most people by using switch-time and let the Switch think that the time is synchronized.
> Maybe something has changed with the latest Firmware? If you're on version 11.0.X. I'm still on 10.0.2. But this are just speculations.

Don't worry and yeah i saw lots of people getting it to work after having used switch time but it doesn't for me. What i don't get is why did the thanksgiving event work while the others don't? Should none of them work then?
Also i'm on 10.0.2 too, i was actually thinking about updating to see if it solved the issue but i guess it has nothing to do with it
Anyway doesn't really matter, i'm not playing the game much, this was mostly for my sister but she's okay with it not working if it can't be helped. There's always next year anyway, and it's not like you're losing items forever if you don't get them right now like idk gachas or whatever.
You can close this if you want, unless you think something else can come out that will solve the issue

**Comment by igromanru** [comment]
Some BCATs aren't checked by time, they got activated on arrival, so I guess it's the case with 1.6.0a (Turkey Day).
It's really a shame that it doesn't work, because there are not just items but the plaza and other places are more beautiful.
Items can be easily save game edited to the game, if you want.
I'll let the issue open for a while, in case someone may find a solution.

**Comment by agronomru** [comment]
Okey, I'll close it for now.
