### ISSUE TITLE
Working on a homebrew app to inject these automatically

### ISSUE THREAD

**Issue by iUltimateLP** [agronomru/ACNH-BCATs#8]
Hey there!
Thanks for all the work to get the BCATs always new and fresh and post them here. I am thinking about writing a homebrew app which will automatically patch in the events, and I've already had success using libnx and the system BCAT partition. Would you be interested to help me with this project when it comes to supplying the BCAT?

Thanks!

**Comment by fullmetal1** [comment]
Can't you just wget from latest release and install from there? The repo is public. There should be no hurdles besides programmatic.

**Comment by igromanru** [comment]
The best I can do is publish them somewhere. I'm actually already doing it here.
You can even get them from the latest release or maybe even easier, directly from the repo:
https://github.com/agronomru/ACNH-BCATs/tree/master/resources/BCAT_files
You can add me on Discord: removed
